all:
  vars:
    control_plane_endpoint: 10.0.0.30
    load_balancer_ip_pool:
      - 10.0.0.224/27
metal:
  children:
    masters:
      hosts:
        motherfucker: {ansible_host: 10.0.0.27, mac: '00:23:24:d1:f5:69', disk: nvme0n1, network_interface: eno1}
        fart: {ansible_host: 10.0.0.28, mac: 'd8:9e:f3:96:fa:1e', disk: sda, network_interface: enp0s31f6}
        twat: {ansible_host: 10.0.0.29, mac: 'fc:3f:db:0b:3a:c9', disk: nvme0n1, network_interface: eno1}
#    workers:
#      hosts:
#        metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
